apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-chaos-workload
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    artisan.io/managed: "true"
    app.kubernetes.io/name: longhorn-chaos-workload
    app.kubernetes.io/part-of: longhorn-validation
