---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-integration-service-config
  namespace: sample-integration-service
  labels:
    app.kubernetes.io/name: sample-integration-service
    app.kubernetes.io/part-of: sample-integration-service
data:
  config.yml: |
    Port: :8080
    AllowDebugLogger: true
    HealthcheckSuccessMessage: "Success"
    ReadHeaderTimeoutSeconds: 30

    ClusterId: "${CLUSTER_ID}"

    LogLevel: "info"
