---
apiVersion: v1
kind: Namespace
metadata:
  name: sample-integration-service
  labels:
    name: sample-integration-service
    app.kubernetes.io/name: sample-integration-service
    app.kubernetes.io/part-of: sample-integration-service
