---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: alloy
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      chart: alloy
      interval: 5m0s
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: default
      version: '1.1.*'
