---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: alloy
  namespace: default
spec:
  interval: 5m0s
  chart: alloy
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: grafana
  version: '1.1.*'
