---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.9.0
    helm:
      releaseName: longhorn
      valuesObject:
        defaultSettings:
          logLevel: Info
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
